name: Liquibase

on:
  push:
    branches:
      - master

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Liquibase
        run: |
          wget -O liquibase.tar.gz https://github.com/liquibase/liquibase/releases/download/v4.26.0/liquibase-4.26.0.tar.gz
          tar -xzf liquibase.tar.gz
          chmod +x liquibase
          sudo mv liquibase /usr/local/bin/
      #descargar mysql connector desde el repository
      - name: Descargar mysql connector
        run: |
          wget -O mysql-connector-java-8.0.27.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.27/mysql-connector-java-8.0.27.jar
          mv mysql-connector-java-8.0.27.jar /usr/local/bin/

      - name: Run Liquibase
        run: |
          ./liquibase/bin/liquibase update --url=jdbc:mysql://localhost:3

        env:
          LIQUIBASE_VERSION: 4.26.0
        continue-on-error: false
