name: Liquibase

on:
  push:
    branches:
      - main

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Liquibase
        run: |
          wget -O liquibase.tar.gz https://github.com/liquibase/liquibase/releases/download/v4.26.0/liquibase-4.26.0.tar.gz
          tar -xzf liquibase.tar.gz
          chmod +x liquibase
          sudo mv liquibase /usr/local/bin/

      - name: Run Liquibase
        run: |
          /usr/local/bin/liquibase --changeLogFile=db/changelog.xml --url=jdbc:mysql://localhost:3306/demo_mysql --username=root --password= update
        env:
          LIQUIBASE_VERSION: 4.26.0
        continue-on-error: true
