name: Liquibase

on:
  push:
    branches:
      - master

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Install Liquibase
        run: |
          wget -O liquibase.tar.gz
          tar -xzf liquibase.tar.gz
          cd liquibase
          mvn clean install -DskipTests
          sudo mv liquibase /usr/local/bin/
          

      # Descargar mysql connector desde el repositorio Maven
      - name: Descargar mysql connector
        run: |
          wget -O mysql-connector-java-8.0.27.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.27/mysql-connector-java-8.0.27.jar
          sudo mv mysql-connector-java-8.0.27.jar /usr/local/bin/

      - name: Run Liquibase
        run: |
          liquibase --url=jdbc:mysql://localhost:3306/demo_mysql --username=root --password= update

        env:
          LIQUIBASE_VERSION: 4.26.0
        continue-on-error: false
